# Generated by Django 3.2.8 on 2021-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_network_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='construction',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
