# Generated by Django 3.2.8 on 2021-10-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_network_construction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rezult',
        ),
    ]
