# Generated by Django 3.2.8 on 2021-10-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_delete_rezult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='statement',
        ),
    ]
