# Generated by Django 3.2.8 on 2021-10-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_network_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='street',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
