# Generated by Django 3.2.8 on 2021-10-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('house', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SocialStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_statuses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.IntegerField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
    ]
